export const INCREMENT_PRICE = `INCREMENT_PRICE`;
export type INCREMENT_PRICE = typeof INCREMENT_PRICE;

export const DECREMENT_PRICE = `DECREMENT_PRICE`;
export type DECREMENT_PRICE = typeof DECREMENT_PRICE;